#----------------------------------------------------------------------
# $Id$
#
# Display the xls files generated by GlossaryTermAudioReview.py
# Gives a user a second (or third, etc.) chance to download one.
#
# When a user has reviewed all terms in a zipfile, the
# GlossaryTermAudioReview.py program generates a spreadsheet with any
# terms that need to be re-recorded by Vanessa.  It is sent by http to
# the user's workstation.  The user is then supposed to save it and
# email it to Vanessa.
#
# Sometimes that misfires.  The user closes the spreadsheet without saving
# it.  Now what should they do?  This program was intended to enable the
# user to download another copy from the saved archive in the REVDIR
# defined in the script.
#
# I never finished it to the point of making it work because it was a
# trivial problem for me or one of the other programmers to simply go into
# the REVDIR directory and email the required file to William at CIAT.  We've
# only had to do that a few times.
#
# !!! THIS PROGRAM DOES NOT YET WORK !!!
#
# BZIssue::5103
#                                           AHM
#                                           September, 2011
#----------------------------------------------------------------------
import os, re, cdrcgi, cgitb
cgitb.enable

# Constants
SCRIPT  = "GlossaryTermAudioRevFiles.py"
HEADER  = "Glossary Term Audio Review Generated Zipfiles"
BUTTONS = ()
ZIPDIR  = "d:/cdr/Audio_from_CIPSFTP"
REVDIR  = u"d:/cdr/Audio_from_CIPSFTP/GeneratedRevisionSheets" % ZIPDIR
XLSPAT  = re.compile("Week_Rev*xls")

# Open the directory and get the names of all of the xls files
xlsList = os.listdir(REVDIR)

# Filter out non-xls files
for xlsFile in xlsList:
    if not XLSPAT.match(xlsFile):
        xlsList.remove(xlsFile)

# Sort into reverse order
xlsList.sort()
xlsList.reverse()

# Create web page
html = cdrcgi.header(HEADER + " - Select File", HEADER,
                    "Click a file to view or download",
                    script=SCRIPT, buttons=())
html += """
   <style type="text/css">
    content { margin-left: 2 cm;  }
    td      { font-size:  14pt; }
    table.tr { margin-left: 2 cm;  }
   </style>

   <div class='content'>
"""

html += u"<table border='1' align='center'>\n"
for xlsFile in xlsList:

    # XXX - TOTALLY WRONG - FIX.ME
    # xlsLine = u"  <tr><td><a href='http://%s/%s'>%s</a></td></tr>\n" % \
    #            (REVDIR, xlsFile, xlsFile)
    html += xlsLine

html += u"""
 </table>
 </div>
</form>
</body>
</html>
"""

cdrcgi.sendPage(html)
