#----------------------------------------------------------------------
#
# $Id$
#
# "We need a newly published trials report which lists InScope Protocol
# and CTGov trials that have published versions, but do not have a
# previously published version. The report will be generated by a user
# selected date range.
#
# This report has the same fields as the newly publishable trials report,
# but it will also include totals.Report identifying unpublished trials
# with publishable versions." [Sheri Khana, request #2443]
#
# Note that this script is given the name it has to avoid conflicts
# with NewlyPublishedTrials.py, a report that was retired a little
# over two years ago.
#
# BZIssue::2443
# BZIssue::5011
#
#----------------------------------------------------------------------
import cdrdb, ExcelWriter, sys, time, cdrcgi, cgi
import datetime

#----------------------------------------------------------------------
# Set the form variables.
#----------------------------------------------------------------------
fields  = cgi.FieldStorage()
session = cdrcgi.getSession(fields)
request = cdrcgi.getRequest(fields)
startDate = fields and fields.getvalue('start') or None
endDate   = fields and fields.getvalue('end') or None
SUBMENU = "Report Menu"
buttons = ["Submit Request", SUBMENU, cdrcgi.MAINMENU, "Log Out"]
script  = "NewlyPublishedTrials2.py"
title   = "CDR Administration"
section = "Newly Published Trials Report"
header  = cdrcgi.header(title, title, section, script, buttons)

#----------------------------------------------------------------------
# Make sure we're logged in.
#----------------------------------------------------------------------
if not session: cdrcgi.bail('Unknown or expired CDR session.')

#----------------------------------------------------------------------
# Handle navigation requests.
#----------------------------------------------------------------------
if request == cdrcgi.MAINMENU:
    cdrcgi.navigateTo("Admin.py", session)
elif request == SUBMENU:
    cdrcgi.navigateTo("Reports.py", session)
elif request == "Log Out":
    cdrcgi.logout(session)

#----------------------------------------------------------------------
# Validate parameters
#----------------------------------------------------------------------
cdrcgi.valParmVal(request, valList=buttons, empty_ok=True)
cdrcgi.valParmDate(startDate, empty_ok=True)
cdrcgi.valParmDate(endDate, empty_ok=True)

#----------------------------------------------------------------------
# If we don't have a request, put up the request form.
#----------------------------------------------------------------------
if not (startDate and endDate):
    opts = {
        "buttons": buttons,
        "action": script,
        "subtitle": section,
        "session": session
    }
    form = cdrcgi.Page(title, **opts)
    end = datetime.date.today()
    start = end - datetime.timedelta(7)
    form.add("<fieldset>")
    form.add(form.B.LEGEND("Date Range"))
    form.add_date_field("start", "Start Date", value=start)
    form.add_date_field("end", "End Date", value=end)
    form.add("</fieldset>")
    form.send()

class Protocol:
    def __init__(self, id, docType, date, user):
        self.id                 = id
        self.docType            = docType
        self.date               = date
        self.user               = user
        self.status             = None
        self.reviewApprovalType = ''
        self.primaryIds         = set()
        self.studyCats          = set()
        self.specialCats        = set()
        self.sourceNames        = set()
        self.submissionComplete = set()

inScope    = {}
ctGov      = {}
prots      = {}
debug      = False # True
statuses   = {}
sources    = {}
approvals  = {}
categories = {}

def show(what):
    if debug:
        sys.stderr.write(what + '\n')

def fixString(s):
    if not s:
        return u""
    return unicode(s)

def fixList(values):
    return u", ".join([fixString(v) for v in values])

def getDateRange():
    return "%s through %s" % (startDate, endDate)

def createSortedList(valueSet):
    valueList = list(valueSet)
    valueList.sort()
    return valueList

def writeTotals(sheet, values, title, rowNum):
    row = sheet.addRow(rowNum, tformat3)
    row.addCell(1, title)
    rowNum += 1
    keys = values.keys()
    keys.sort()
    for key in keys:
        row = sheet.addRow(rowNum)
        row.addCell(1, key, style=lformat)
        row.addCell(2, values[key], style=rformat)
        rowNum += 1
    return rowNum + 2

def addTotalsSheet(workbook, prots, inScope, ctGov):
    worksheet = workbook.addWorksheet('Totals')
    worksheet.addCol(1, 150)
    worksheet.addCol(2, 25)
    row = worksheet.addRow(1, tformat1)
    row.addCell(1, "Newly Published Trials", mergeAcross=7)
    row = worksheet.addRow(2, tformat1)
    row.addCell(1, getDateRange(), mergeAcross=7)
    row = worksheet.addRow(4, tformat2)
    row.addCell(1, "InScope and CTGov Totals")

    r = writeTotals(worksheet, categories, "Study Category",          6)
    r = writeTotals(worksheet, statuses,   "Current Protocol Status", r)
    r = writeTotals(worksheet, sources,    "Protocol Source",         r)
    r = writeTotals(worksheet, approvals,  "Approval",                r)

def addWorksheet(workbook, title, headers, widths, prots):
    worksheet = workbook.addWorksheet(title)
    for col in range(len(headers)):
        worksheet.addCol(col + 1, widths[col])
    row = worksheet.addRow(1, tformat1)
    row.addCell(1, "Newly Published Trials", mergeAcross=len(headers) - 1)
    row = worksheet.addRow(2, tformat1)
    row.addCell(1, getDateRange(), mergeAcross=len(headers) - 1)
    row = worksheet.addRow(4, tformat2)
    row.addCell(1, "%s Protocols" % title)
    row = worksheet.addRow(6, hdrFormat)
    for col in range(len(headers)):
        row.addCell(col + 1, headers[col])
    keys = prots.keys()
    for key in keys:
        prot             = prots[key]
        prot.primaryIds  = createSortedList(prot.primaryIds)
        prot.studyCats   = createSortedList(prot.studyCats)
        prot.specialCats = createSortedList(prot.specialCats)
        prot.sourceNames = createSortedList(prot.sourceNames)
        prot.submissionComplete = createSortedList(prot.submissionComplete)
    def sorter(a, b):
        result = cmp(prots[a].studyCats, prots[b].studyCats)
        if result:
            return result
        return cmp(a, b)
    keys.sort(sorter)
    r = 7
    for key in keys:
        prot = prots[key]
        nRows = len(prot.studyCats) or 1
        for rowNum in range(nRows):
            row = worksheet.addRow(r, lformat)
            c = 1
            row.addCell(c, `prot.id`)
            c += 1
            row.addCell(c, fixList(prot.primaryIds))
            c += 1
            if prot.studyCats:
                row.addCell(c, fixString(prot.studyCats[rowNum]))
            c += 1
            if title == 'InScope':
                row.addCell(c, fixList(prot.specialCats))
                c += 1
            row.addCell(c, fixString(prot.status))
            c += 1
            if title == 'InScope':
                row.addCell(c, fixList(prot.sourceNames))
                c += 1
                row.addCell(c, fixString(prot.reviewApprovalType))
                c += 1
                row.addCell(c, fixList(prot.submissionComplete))
                c += 1
            row.addCell(c, prot.date and prot.date[:10] or "")
            c += 1
            row.addCell(c, fixString(prot.user))
            r += 1
    r += 2
    row = worksheet.addRow(r, tformat3)
    row.addCell(1, "Total: %d" % len(prots))

if sys.platform == "win32":
    import os, msvcrt
    msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

#----------------------------------------------------------------------
# Start by creating a list of all protocols first published in the
# date range specified by the user.
#----------------------------------------------------------------------
conn = cdrdb.connect('CdrGuest')
# conn.setAutoCommit()
cursor = conn.cursor()
cursor.execute("""\
    CREATE TABLE #trials
             (id INT         NOT NULL,
        doc_type VARCHAR(32) NOT NULL,
         pub_job INT         NOT NULL,
        pub_date DATETIME    NOT NULL)""")
conn.commit()
show("#trials table created")
cursor.execute("""\
    INSERT INTO #trials (id, doc_type, pub_job, pub_date)
    SELECT d.id, t.name, MIN(e.id), MIN(e.completed)
      FROM document d
      JOIN doc_type t
        ON t.id = d.doc_type
      JOIN published_doc p
        ON p.doc_id = d.id
      JOIN pub_event e
        ON e.id = p.pub_proc
     WHERE t.name in ('InScopeProtocol', 'CTGovProtocol')
       AND e.pub_subset LIKE 'Push_Documents_To_Cancer.Gov%%'
       AND e.pub_subset NOT LIKE '%%-Remove'
  GROUP BY d.id, t.name
    HAVING MIN(e.completed) BETWEEN '%s' AND '%s 23:59:59'""" % (startDate,
                                                                 endDate),
               timeout = 300)
conn.commit()
show("#trials table filled")

#----------------------------------------------------------------------
# Next we create objects for each of the protocols in the report.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT t.id, t.doc_type, t.pub_date, u.name
      FROM #trials t
      JOIN pub_proc_doc d
        ON d.doc_id = t.id
       AND d.pub_proc = t.pub_job
      JOIN doc_version v
        ON v.id = t.id
       AND v.num = d.doc_version
      JOIN usr u
        ON u.id = v.usr""", timeout = 300)
for docId, docType, pubDate, userName in cursor.fetchall():
    p = prots[docId] = Protocol(docId, docType, pubDate, userName)
    if p.docType == 'InScopeProtocol':
        inScope[docId] = p
    else:
        ctGov[docId] = p
show("protocol objects created")

#----------------------------------------------------------------------
# Fill in the protocol status values.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE path IN ('/InScopeProtocol/ProtocolAdminInfo/CurrentProtocolStatus',
                    '/CTGovProtocol/OverallStatus')""", timeout = 300)
for docId, status in cursor.fetchall():
    status = status.strip()
    statuses[status] = statuses.get(status, 0) + 1
    prots[docId].status = status.strip()
show("status values added")

#----------------------------------------------------------------------
# Fill in the protocol primary IDs.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path IN ('/InScopeProtocol/ProtocolIDs/PrimaryID/IDString',
                      '/CTGovProtocol/IDInfo/OrgStudyID')""", timeout = 300)
for docId, protId in cursor.fetchall():
    prots[docId].primaryIds.add(protId)
show("primary IDs added")

#----------------------------------------------------------------------
# Fill in the protocol study categories.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path IN ('/CTGovProtocol/PDQIndexing/StudyCategory' +
                      '/StudyCategoryName',
                      '/InScopeProtocol/ProtocolDetail' +
                      '/StudyCategory/StudyCategoryName')""", timeout = 300)
for docId, value in cursor.fetchall():
    category = value.strip()
    prots[docId].studyCats.add(category)
    categories[category] = categories.get(category, 0) + 1
show("study categories added")

cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path = '/InScopeProtocol/ProtocolSpecialCategory'
                  + '/SpecialCategory'""", timeout = 300)
for docId, value in cursor.fetchall():
    prots[docId].specialCats.add(value.strip())
show("special categories added")

#----------------------------------------------------------------------
# Next we get the review approval type values.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path = '/InScopeProtocol/ProtocolApproval'
                  + '/ReviewApprovalType'""", timeout = 300)
for docId, value in cursor.fetchall():
    approval = value.strip()
    prots[docId].reviewApprovalType = approval
    approvals[approval] = approvals.get(approval, 0) + 1
show("review approval types added")

#----------------------------------------------------------------------
# Finally, collect the protocol source names.
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path = '/InScopeProtocol/ProtocolSources/ProtocolSource'
                  + '/SourceName'""", timeout = 300)
for docId, value in cursor.fetchall():
    source = value.strip()
    prots[docId].sourceNames.add(source)
    sources[source] = sources.get(source, 0) + 1
show("protocol source names added")

#----------------------------------------------------------------------
# New column requested by Sheri (#4057).
#----------------------------------------------------------------------
cursor.execute("""\
    SELECT q.doc_id, q.value
      FROM query_term q
      JOIN #trials t
        ON t.id = q.doc_id
     WHERE q.path = '/InScopeProtocol/ProtocolSources/ProtocolSource'
                  + '/DateSubmissionComplete'""", timeout = 300)
for docId, value in cursor.fetchall():
    date = value.strip()
    prots[docId].submissionComplete.add(date)
show("submission completion dates added")

#----------------------------------------------------------------------
# Create the report.
#----------------------------------------------------------------------
t = time.strftime("%Y%m%d%H%M%S")
if not debug:
    print "Content-type: application/vnd.ms-excel"
    print ("Content-Disposition: attachment; "
           "filename=NewlyPublishedTrials-%s.xls" % t)
    print

workbook = ExcelWriter.Workbook()
show("workbook created")
align = ExcelWriter.Alignment('Center', wrap=True)
font = ExcelWriter.Font(bold=True)
hdrFormat = workbook.addStyle(alignment=align, font=font)
tformat3 = workbook.addStyle(font=font)
align = ExcelWriter.Alignment('Center')
font = ExcelWriter.Font(bold=True, size=16)
tformat1 = workbook.addStyle(alignment=align, font=font)
align = ExcelWriter.Alignment('Left')
font = ExcelWriter.Font(bold=True, size=12)
tformat2 = workbook.addStyle(alignment=align, font=font)
lformat = workbook.addStyle(alignment=align)
align = ExcelWriter.Alignment('Right')
rformat = workbook.addStyle(alignment=align)
titles  = ('InScope', 'CTGov')
headers = (
    ('DocID', 'ProtocolID','Study Category', 'Special Category',
     'Current\nProtocol\nStatus', 'Source', 'Approval',
     'Date\nSubmission\nComplete', 'Date\nPublished', 'User'),
    ('DocID', 'OrgStudyID', 'Study Category', 'Overall\nStatus',
     'Date Published', 'User')
    )
widths  = (
    (50, 150, 100, 100, 100, 100, 100, 100, 100, 75),
    (50, 150, 100, 100, 100, 75)
    )
addTotalsSheet(workbook, prots, inScope, ctGov)
addWorksheet(workbook, titles[0], headers[0], widths[0], inScope)
show("%s worksheet created" % titles[0])
addWorksheet(workbook, titles[1], headers[1], widths[1], ctGov)
show("%s worksheet created" % titles[1])
workbook.write(sys.stdout, True)
show("done")
